#
# Generated by erpcgen 1.3.0 on Mon Sep  5 16:12:50 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# This const defines the matrix size. The value has to be the same as the 
#Matrix array dimension. Do not forget to re-generate the erpc code once the 
#matrix size is changed in the erpc file
matrix_size = 5


