#
# Generated by erpcgen 1.3.0 on Mon Sep  5 16:12:50 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for MatrixMultiplyService
class IMatrixMultiplyService(object):
    SERVICE_ID = 1
    ERPCMATRIXMULTIPLY_ID = 1

    def erpcMatrixMultiply(self, matrix1, matrix2, result_matrix):
        raise NotImplementedError()


